### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by chrism** [yappbox/yapp-scroll-view#43]
Hi,

I’m trying to develop an interactive map which can be zoomed and panned using Ember JS.

After a bit of searching this addon looks like it might be great and exactly what I need. 😀

Because there doesn’t appear to be any documentation yet I’m not yet sure if that is the case, though.

It seems like the project is active with recent commits so a have a couple of quick questions if you don’t mind.

- would you recommend using this, or is it internal?
- if yes, are there any guides/help beyond reading the source and tests?
- would you consider a PR to help with documentation if I am able to use it?

Thanks!

**Comment by lukemelia** [comment]
@chrism This is internal and I wouldn't recommend using it. Feel free to borrow code and concepts at will, though!

**Comment by chrism** [comment]
@lukemelia Thanks for the quick reply, will do!
